### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by safareli** [Thimoteus/purescript-optlicative#1]
last release results in warning:

```
in module Node.Optlicative.Internal

  Name takeDrop was shadowed.

in value declaration takeDropWhile
```

which is fixed in master, but there is no new public release :(

**Comment by Thimoteus** [comment]
Updated, went from 0.4.1 to 4.0.2 (whoops).

**Comment by safareli** [comment]
I think it could be possible to delete release and create new one :p

Thanks anyway!
