### ISSUE TITLE
Provide function for parsing options without a command

### ISSUE THREAD

**Issue by paluh** [Thimoteus/purescript-optlicative#6]
Hi,

Thanks for great library!

I'm not sure if I missing something but it seems that current API forces users to define commands record to run `oplicate`.
I think that it would be useful to provide a function which facilitates use of `Optlicative` parser directly without additional record/command definition.

P.S.
I can try to provide a PR of course.

**Comment by Thimoteus** [comment]
Hey, you can always just provide an empty record:

```
main :: Effect Unit
main = do
  {value} <- optlicate {} prefs
  unV
    (\errs -> do
      Console.log "Errors occurred:"
      logErrors errs
    )
    (\{file} -> runProgram file)
    value
```

That's an example from a real project I've written.

**Comment by paluh** [comment]
Thanks for this example @Thimoteus!
